name: Validate Terraform Format

on:
  pull_request:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Terraform Format Check
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Fetch changed files
        id: pr_files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "space-delimited"

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Validate terraform fmt
        run: |
          set +e
          for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
            if [[ $changed_file == *.tf ]]; then
              terraform fmt -check $changed_file || exit 1
            fi
          done

  terraform-validate:
    runs-on: ubuntu-latest
    needs: validate
    name: Terraform Validation
    steps:
      - uses: actions/checkout@v3

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
